[project]
name = "webvoyager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.4",
    "openai>=2.6.1",
    "pillow>=12.0.0",
    "requests>=2.32.5",
    "selenium==4.15.2",
]
